---

- name: Installation des paquets
  yum:
    name:
      - httpd
      - php
      - php-mysql
    state: present

- name: Redemarrage Apache
  systemd:
    name: httpd
    enabled: yes
    state: restarted

- name: ouverture du port 80 pour l'acces en HTTP
  firewalld:
    port: http
    permanent: yes
    state: enabled
    immediate: true
    
- name: reload du firewall
  systemd:
    firewalld: http
    state: reloaded

- name: Droite d'acces au dossier HTTP
  file:
   path: /var/www/html
   state: directory
   mode: 0755
   
- name: copie app
  copy:
    src: app/
    dest: /var/www/html

# tasks file for apache
